config/routes.rb
Rails.application.routes.draw do
  resources :calculos
  resources :renda_fixas
  get 'home/index'

end

app/models/calculo.rb
class Calculo < ActiveRecord::Base
  belongs_to :renda_fixa
  validates :valor_inicial,  presence: true
  validates :valor_mensal,  presence: true
  
  
  def calcularRendimentoTeste
    
    dias = ((self.data_de_retirada || self.renda_fixa.vencimento) - Date.today).to_f
    meses = (dias / 30).to_i
    taxa = ((self.renda_fixa.indice.taxa_de_juros + self.renda_fixa.taxa_de_juros) / 100) + 1
    taxa = (taxa ** (1 / 12.0))
    valor_bruto = self.valor_inicial;
    valor_investido = self.valor_inicial;
    meses.times do |i|
      valor_bruto = valor_bruto * taxa.round(4)
      valor_bruto = valor_bruto + self.valor_mensal
      valor_investido += self.valor_mensal
    end
    valor_bruto.round(2).to_f
    Rendimento.new(valor_bruto, valor_investido, self.renda_fixa)
  end
  
  def calcularRendimento
    dias = ((self.data_de_retirada || self.renda_fixa.vencimento) - Date.today).to_f
    meses = (dias / 30).to_i
    taxa = ((self.renda_fixa.indice.taxa_de_juros + self.renda_fixa.taxa_de_juros) / 100) + 1
    taxa = (taxa ** (1 / 12.0))
    valor_bruto = self.valor_inicial;
    valor_investido = self.valor_inicial;
    meses.times do |i|
      valor_bruto = valor_bruto * taxa.round(4)
      valor_bruto = valor_bruto + self.valor_mensal
      valor_investido += self.valor_mensal
    end
    rendimento_bruto = valor_bruto - valor_investido
    valor_imposto = rendimento_bruto * (imposto_de_renda(meses, self.renda_fixa) / 100)
    Rendimento.new(valor_investido, valor_bruto, valor_imposto)
  end
  
  def imposto_de_renda(meses, renda)
    if renda.has_imposto_de_renda
      return renda.imposto_de_renda if renda.is_imposto_de_renda_fixo
      case
      when meses < 6
        return 22.5
      when meses >= 6 && meses < 12
        return 20.0
      when meses >= 12 && meses < 24
        return 17.5
      else
        return 15.0
      end
    else
      return 0.0
    end
  end
  
end

app/models/indice.rb
class Indice < ActiveRecord::Base
    has_many :renda_fixa
    validates :indexador,  presence: true
    validates :taxa_de_juros, presence: true
end

app/models/renda_fixa.rb
class RendaFixa < ActiveRecord::Base
    belongs_to :indice
    validates :indice, absence: false
    validates :titulo,  presence: true
    validates :vencimento,  presence: true
    validates :taxa_de_juros,  presence: true
    validates :tipo,  presence: true
    validates :imposto_de_renda,  presence: true
    validates :has_imposto_de_renda, exclusion: { in: [nil] }
    validates :is_imposto_de_renda_fixo, exclusion: { in: [nil] }
    
    
end

app/models/rendimento.rb
class Rendimento
    
    def initialize(valor_investido, valor_bruto, valor_imposto)
        @valor_investido = valor_investido
        @valor_bruto = valor_bruto
        @rendimento_bruto = valor_bruto - valor_investido
        @valor_imposto = valor_imposto
        @rendimento_liquido = rendimento_bruto - valor_imposto
        @valor_liquido = @valor_investido + @rendimento_liquido
    end
    
    def valor_investido
        @valor_investido.round(2).to_f
    end
    
    def valor_bruto
        @valor_bruto.round(2).to_f
    end
    
    def rendimento_bruto
        @rendimento_bruto.round(2).to_f
    end
    
    def valor_imposto
        @valor_imposto.round(2).to_f
    end
    
    def rendimento_liquido
        @rendimento_liquido.round(2).to_f
    end
    
    def valor_liquido
        @valor_liquido.round(2).to_f
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calculos_controller.rb
class CalculosController < ApplicationController
  before_action :set_calculo, only: [:show, :edit, :update, :destroy]

  # GET /calculos
  # GET /calculos.json
  def index
    @calculos = Calculo.all
  end

  # GET /calculos/1
  # GET /calculos/1.json
  def show
  end

  # GET /calculos/new
  def new
    @calculo = Calculo.new
  end

  # GET /calculos/1/edit
  def edit
  end

  # POST /calculos
  # POST /calculos.json
  def create
    @calculo = Calculo.new(calculo_params)

    respond_to do |format|
      if @calculo.save
        format.html { redirect_to @calculo, notice: 'Calculo was successfully created.' }
        format.json { render :show, status: :created, location: @calculo }
      else
        format.html { render :new }
        format.json { render json: @calculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calculos/1
  # PATCH/PUT /calculos/1.json
  def update
    respond_to do |format|
      if @calculo.update(calculo_params)
        format.html { redirect_to @calculo, notice: 'Calculo was successfully updated.' }
        format.json { render :show, status: :ok, location: @calculo }
      else
        format.html { render :edit }
        format.json { render json: @calculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calculos/1
  # DELETE /calculos/1.json
  def destroy
    @calculo.destroy
    respond_to do |format|
      format.html { redirect_to calculos_url, notice: 'Calculo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calculo
      @calculo = Calculo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calculo_params
      params.require(:calculo).permit(:valor_inicial, :valor_mensal, :data_de_retirada, :renda_fixa_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/indice_controller.rb
class IndiceController < ApplicationController
end

app/controllers/renda_fixas_controller.rb
class RendaFixasController < ApplicationController
  before_action :set_renda_fixa, only: [:show, :edit, :update, :destroy]

  # GET /renda_fixas
  # GET /renda_fixas.json
  def index
    @renda_fixas = RendaFixa.all
  end

  # GET /renda_fixas/1
  # GET /renda_fixas/1.json
  def show
  end

  # GET /renda_fixas/new
  def new
    @renda_fixa = RendaFixa.new
  end

  # GET /renda_fixas/1/edit
  def edit
  end

  # POST /renda_fixas
  # POST /renda_fixas.json
  def create
    @renda_fixa = RendaFixa.new(renda_fixa_params)

    respond_to do |format|
      if @renda_fixa.save
        format.html { redirect_to @renda_fixa, notice: 'Renda fixa was successfully created.' }
        format.json { render :show, status: :created, location: @renda_fixa }
      else
        format.html { render :new }
        format.json { render json: @renda_fixa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /renda_fixas/1
  # PATCH/PUT /renda_fixas/1.json
  def update
    respond_to do |format|
      if @renda_fixa.update(renda_fixa_params)
        format.html { redirect_to @renda_fixa, notice: 'Renda fixa was successfully updated.' }
        format.json { render :show, status: :ok, location: @renda_fixa }
      else
        format.html { render :edit }
        format.json { render json: @renda_fixa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /renda_fixas/1
  # DELETE /renda_fixas/1.json
  def destroy
    @renda_fixa.destroy
    respond_to do |format|
      format.html { redirect_to renda_fixas_url, notice: 'Renda fixa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_renda_fixa
      @renda_fixa = RendaFixa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def renda_fixa_params
      params.require(:renda_fixa).permit(:titulo, :vencimento, :taxa_de_juros, :tipo, :imposto_de_renda, :is_imposto_de_renda_fixo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculos_helper.rb
module CalculosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/indice_helper.rb
module IndiceHelper
end

app/helpers/renda_fixas_helper.rb
module RendaFixasHelper
end

app/views/calculos/_form.html.erb
<%= form_for(@calculo) do |f| %>
  <% if @calculo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calculo.errors.count, "error") %> prohibited this calculo from being saved:</h2>

      <ul>
      <% @calculo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :valor_inicial %><br>
    <%= f.text_field :valor_inicial %>
  </div>
  <div class="field">
    <%= f.label :valor_mensal %><br>
    <%= f.text_field :valor_mensal %>
  </div>
  <div class="field">
    <%= f.label :data_de_retirada %><br>
    <%= f.date_select :data_de_retirada %>
  </div>
  <div class="field">
    <%= f.label :renda_fixa_id %><br>
    <%= f.text_field :renda_fixa_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calculos/edit.html.erb
<h1>Editing Calculo</h1>

<%= render 'form' %>

<%= link_to 'Show', @calculo %> |
<%= link_to 'Back', calculos_path %>

app/views/calculos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Calculos</h1>

<table>
  <thead>
    <tr>
      <th>Valor inicial</th>
      <th>Valor mensal</th>
      <th>Data de retirada</th>
      <th>Renda fixa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calculos.each do |calculo| %>
      <tr>
        <td><%= calculo.valor_inicial %></td>
        <td><%= calculo.valor_mensal %></td>
        <td><%= calculo.data_de_retirada %></td>
        <td><%= calculo.renda_fixa %></td>
        <td><%= link_to 'Show', calculo %></td>
        <td><%= link_to 'Edit', edit_calculo_path(calculo) %></td>
        <td><%= link_to 'Destroy', calculo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Calculo', new_calculo_path %>

app/views/calculos/new.html.erb
<h1>New Calculo</h1>

<%= render 'form' %>

<%= link_to 'Back', calculos_path %>

app/views/calculos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Valor inicial:</strong>
  <%= @calculo.valor_inicial %>
</p>

<p>
  <strong>Valor mensal:</strong>
  <%= @calculo.valor_mensal %>
</p>

<p>
  <strong>Data de retirada:</strong>
  <%= @calculo.data_de_retirada %>
</p>

<p>
  <strong>Renda fixa:</strong>
  <%= @calculo.renda_fixa %>
</p>

<%= link_to 'Edit', edit_calculo_path(@calculo) %> |
<%= link_to 'Back', calculos_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/renda_fixas/_form.html.erb
<%= form_for(@renda_fixa) do |f| %>
  <% if @renda_fixa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@renda_fixa.errors.count, "error") %> prohibited this renda_fixa from being saved:</h2>

      <ul>
      <% @renda_fixa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :vencimento %><br>
    <%= f.date_select :vencimento %>
  </div>
  <div class="field">
    <%= f.label :taxa_de_juros %><br>
    <%= f.text_field :taxa_de_juros %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :imposto_de_renda %><br>
    <%= f.text_field :imposto_de_renda %>
  </div>
  <div class="field">
    <%= f.label :is_imposto_de_renda_fixo %><br>
    <%= f.check_box :is_imposto_de_renda_fixo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/renda_fixas/edit.html.erb
<h1>Editing Renda Fixa</h1>

<%= render 'form' %>

<%= link_to 'Show', @renda_fixa %> |
<%= link_to 'Back', renda_fixas_path %>

app/views/renda_fixas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Renda Fixas</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Vencimento</th>
      <th>Taxa de juros</th>
      <th>Tipo</th>
      <th>Imposto de renda</th>
      <th>Is imposto de renda fixo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @renda_fixas.each do |renda_fixa| %>
      <tr>
        <td><%= renda_fixa.titulo %></td>
        <td><%= renda_fixa.vencimento %></td>
        <td><%= renda_fixa.taxa_de_juros %></td>
        <td><%= renda_fixa.tipo %></td>
        <td><%= renda_fixa.imposto_de_renda %></td>
        <td><%= renda_fixa.is_imposto_de_renda_fixo %></td>
        <td><%= link_to 'Show', renda_fixa %></td>
        <td><%= link_to 'Edit', edit_renda_fixa_path(renda_fixa) %></td>
        <td><%= link_to 'Destroy', renda_fixa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Renda fixa', new_renda_fixa_path %>

app/views/renda_fixas/new.html.erb
<h1>New Renda Fixa</h1>

<%= render 'form' %>

<%= link_to 'Back', renda_fixas_path %>

app/views/renda_fixas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @renda_fixa.titulo %>
</p>

<p>
  <strong>Vencimento:</strong>
  <%= @renda_fixa.vencimento %>
</p>

<p>
  <strong>Taxa de juros:</strong>
  <%= @renda_fixa.taxa_de_juros %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @renda_fixa.tipo %>
</p>

<p>
  <strong>Imposto de renda:</strong>
  <%= @renda_fixa.imposto_de_renda %>
</p>

<p>
  <strong>Is imposto de renda fixo:</strong>
  <%= @renda_fixa.is_imposto_de_renda_fixo %>
</p>

<%= link_to 'Edit', edit_renda_fixa_path(@renda_fixa) %> |
<%= link_to 'Back', renda_fixas_path %>